#!/usr/bin/env bash
#Printing all the time

minutes=0
hours=0
while [[ $minutes -ne 61 && $hours -ne 13 ]]
do
	if (( minutes == 0 ))
	then
		echo "Hour: $hours"
		((minutes++))
	elif (( minutes == 60 ))
	then
		((hours++))
		minutes=0
	else
		echo "$minutes"
		((minutes++))

	fi
done
