#!/usr/bin/env bash
# setup a few rules with firewall (ufw)

sudo apt update
sudo apt dist-upgrade
sudo apt install ufw
sudo ufw status
ufw default allow outgoing
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable